# Generated by Django 5.2.16 on 2026-08-02 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_user'),
        ('doctors', '0003_alter_doctor_consultation_fee_alter_doctor_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'appointment_date', 'status'], name='appt_user_date_status_idx'),
        ),
    ]
