# Generated by Django 5.2.16 on 2026-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.PositiveSmallIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_today', models.BooleanField(default=False)),
                ('languages', models.JSONField(default=list)),
                ('available_days', models.JSONField(default=list)),
                ('initials', models.CharField(max_length=10)),
                ('about', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
